- name: Deploy web server and runners 
  hosts: borg
  become: True
  become_method: sudo
  tags: code 
  tasks:
    # webserver
    - name: pull 
      shell: docker pull crufter/borg-web 
    - name: copy nginx conf
      copy: src=../../../web-client/nginx.conf dest=/var/nginx.conf
    - name: stop running
      shell: sudo docker rm -f borg-web
      ignore_errors: true 
    - name: start container
      shell: docker run -p=80:80 -p=443:443 -v "/etc/letsencrypt/archive/ok-b.org:/etc/cruft" -v /var/sitemap/sitemap.xml.gz:/usr/share/nginx/html/sitemap.xml.gz:ro -v /var/nginx.conf:/etc/nginx/nginx.conf:ro --name=borg-web -d crufter/borg-web
    
